version: '3'

networks:
  mongodb-net:
    driver: bridge

services:
  configs1:
    container_name: configs1
    image: mongo
    entrypoint: ['mongod', '--config', '/etc/mongod.conf']
    ports:
      - 10001:27017
    volumes:
      - configs1:/data/db
      - ./config_mongo/configsvr/configsvr.conf:/etc/mongod.conf
    networks:
      - mongodb-net

  # configs2:
  #   container_name: configs2
  #   image: mongo
  #   entrypoint: ["mongod","--config","/etc/mongo.conf"]
  #   ports:
  #     - 10002:27017
  #   volumes:
  #     - configs2:/data/db
  #     - ./config_mongo/configsvr/configsvr.conf:/etc/mongod.conf
  #   networks:
  #     - mongodb-net

  # configs3:
  #   container_name: configs3
  #   image: mongo
  #   entrypoint: ["mongod","--config","/etc/mongo.conf"]
  #   ports:
  #     - 10003:27017
  #   volumes:
  #     - configs3:/data/db
  #     - ./config_mongo/configsvr/configsvr.conf:/etc/mongod.conf
  #   networks:
  #     - mongodb-net

  shard1s1:
    container_name: shard1s1
    image: mongo
    entrypoint: ['mongod', '--config', '/etc/mongod.conf']
    ports:
      - 50001:27017
    volumes:
      - shard1s1:/data/db
      - ./config_mongo/shards/shards.conf:/etc/mongod.conf
    networks:
      - mongodb-net

  # shard1s2:
  #   container_name: shard1s2
  #   image: mongo
  #   entrypoint: ["mongod","--config","/etc/mongo.conf"]
  #   ports:
  #     - 50002:27017
  #   volumes:
  #     - shard1s2:/data/db
  #   networks:
  #     - mongodb-net

  # shard1s3:
  #   container_name: shard1s3
  #   image: mongo
  #   entrypoint: ["mongod","--config","/etc/mongo.conf"]
  #   ports:
  #     - 50003:27017
  #   volumes:
  #     - shard1s3:/data/db
  #   networks:
  #     - mongodb-net

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/configs1:27017 --port 27017 --bind_ip_all
    ports:
      - 30000:27017
    networks:
      - mongodb-net
# mongos --configdb cfgrs/configs1:27017,configs2:27017,configs3:27017 --port 27017 --bind_ip_all

# sudo docker exec -it mongos mongosh --eval "sh.addShard(\"shard1rs/shard1s1:27017,shard1s2:27017,shard1s3:27017\")"

volumes:
  configs1: {}
  configs2: {}
  configs3: {}
  shard1s1: {}
  shard1s2: {}
  shard1s3: {}
